PL-41 Adding the bulk indicator metadata export to the sdk
trustar/trustar-python pull request #96
Opened 2021-03-23 23:48 UTC by emaginniss

2021-03-30 21:00 UTC, dsolmirano requested changes
I'm concerned about mix and match of 2.0 and 1.3 endpoints. I would use 1.3 and keep here, or use 2.0 and move to the new SDK

2021-04-23 16:35 UTC, emaginniss commented on trustar/indicator_client.py
> +        return None
Done

2021-04-23 16:35 UTC, emaginniss commented on trustar/indicator_client.py
> +        :param int to_time: end of time window in milliseconds since epoch (optional)
There is no max range

2021-04-23 16:36 UTC, emaginniss commented on trustar/examples/indicator_bulk_export.py
> +correctly, the api_endpoint in your config must be for 2.0 (<host>/api/2.0)
This is fixed.  The API endpoints being called have been moved from 2.0 to 1.3.  I have removed the section of the comments that mentioned 2.0

2021-04-23 16:36 UTC, emaginniss commented on trustar/examples/indicator_bulk_export.py
> +while status != "ERROR" and status != "CANCELED" and status != "COMPLETE":
Done

2021-04-23 18:17 UTC, YaPeL approved these changes

2021-04-23 21:02 UTC, dsolmirano approved these changes
LGTM!

2021-04-25 23:28 UTC, merged